### ISSUE TITLE
function power_mu_cov_contrast

### ISSUE THREAD

**Issue by johannjacoby** [langenberg/powerANOVA#1]
Hello,

I have found that the function power_mu_cov_contrast gives the same power for any n (given the same M, Sigma, contrast etc...). I looked into the function and saw that there, n is given over to power_mu_cov with a hard coded value of "n=10". Is this intended?

**Comment by langenberg** [comment]
Hey Johann,
This is indeed not intended. I fixed the line in the code.
Thanks for reporting!
Best,
Benedikt
